import type { NextPage } from "next";
import Head from "next/head";

import Hello from "components/landing/Hello";
import styles from "pages/Landing.module.scss";

const Landing: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Landing - Next App Template</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Hello />
      </main>
    </div>
  );
};

export default Landing;
